# Databricks notebook source
"""script to define cohort creation variables"""

# COMMAND ----------

# all variables related to the cohort initialization step
COL_LSD_GROUP = "LSD_GROUP"
COL_N_CERTAIN_DIAGS = "N_CERTAIN_DIAGS"
COL_N_UNCERTAIN_DIAGS = "N_UNCERTAIN_DIAGS"
COL_N_TREATMENTS = "N_TREATMENTS"
COL_CERTAIN_LSD = "CERTAIN_LSD"
COL_UNCERTAINTY_REASON = "UNCERTAINTY_REASON"

PREFIX_FIRST_DATE = "FIRST"
PREFIX_CERTAIN_DIAG = "CERTAIN"
PREFIX_UNCERTAIN_DIAG = "UNCERTAIN"
CERTAIN_FLAG = True

# COMMAND ----------

# patient informations that need to be computed based on the informations in the database
COL_FIRST_YEAR_ACTIVE = "FIRST_YEAR_ACTIVE"
COL_LAST_YEAR_ACTIVE = "LAST_YEAR_ACTIVE"
COL_FIRST_DATE_ACTIVE = "FIRST_DATE_ACTIVE"
COL_LAST_DATE_ACTIVE = "LAST_DATE_ACTIVE"

COL_AGE_AT_FIRST_ACTIVITY = "AGE_AT_FIRST_ACTIVITY"
COL_AGE_AT_LAST_ACTIVE_DATE = "AGE_AT_LAST_ACTIVE_DATE"

COL_INDEX_DATE = "INDEX_DATE"
COL_YEAR_INDEX_DATE = "YEAR_INDEX_DATE"
COL_AGE_AT_INDEX_DATE = "AGE_AT_INDEX_DATE"

COL_ENROLLMENT_DURATION = "ENROLLMENT_DURATION"
COL_LOOKBACK_PERIOD = "LOOKBACK_PERIOD"